name: Update Badge

on:
  push:
    branches:
      - main # Change this to your default branch name

jobs:
  updateBadge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git Config
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # You can change the Node.js version as needed

      - name: Install Dependencies
        run: npm install

      - name: Run JavaScript Script
        run: |
          node updateBadges.js "${{ secrets.OWNER }}" "${{ secrets.NAME }}" "${{ secrets.ACCESS_TOKEN }}"

      - name: Check for Changes
        run: |
          git diff --exit-code || git commit -m "Update badge" README.md

      - name: Push Changes
        run: |
          git push
